"""empty message

Revision ID: b06eccb1084c
Revises: 
Create Date: 2023-01-30 10:41:56.918235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b06eccb1084c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('gender', sa.String(length=80), nullable=False),
    sa.Column('alive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('lenght', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('type', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('characters_episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_character', sa.Integer(), nullable=True),
    sa.Column('id_episode', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_character'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['id_episode'], ['episodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('episodes_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_episode', sa.Integer(), nullable=True),
    sa.Column('id_location', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_episode'], ['episodes.id'], ),
    sa.ForeignKeyConstraint(['id_location'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_character', sa.Integer(), nullable=True),
    sa.Column('id_episode', sa.Integer(), nullable=True),
    sa.Column('id_location', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_character'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['id_episode'], ['episodes.id'], ),
    sa.ForeignKeyConstraint(['id_location'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    op.drop_table('episodes_locations')
    op.drop_table('characters_episodes')
    op.drop_table('users')
    op.drop_table('locations')
    op.drop_table('episodes')
    op.drop_table('characters')
    # ### end Alembic commands ###
